root: ./

structure:  
    readme: README.md  
    summary: SUMMARY.md

redirects:  
    golden-info./golden-overview-and-faq: README.md
    project-information/golden-overview-and-faq: README.md
    protocol/guides/flagging-triples: protocol/guides/flagging.md